### ISSUE TITLE
Register package at METADATA.jl

### ISSUE THREAD

**Issue by Godisemo** [billmclean/GaussQuadrature.jl#2]
This package is a lot faster than my quick implementation for computing Laguerre quadrature points.

```
function laguerre(n)
  x, v = LAPACK.stev!('V', collect(1.0:2:2*n-1), collect(1.0:n-1))
  w = vec(v[1,:].^2)
  x, w
end
```

Would you mind registering this package so that people (I) can require it for other packages?

**Comment by billmclean** [comment]
I can't promise but I will try over the weekend.  My previous attempt at 
registering the package did not work, but that was a long time ago and I 
gather the system has since changed.

On 12/10/15 01:31, Godisemo wrote:

> This package is a lot faster than my quick implementation for computing
> Laguerre quadrature points.
> 
> |function laguerre(n) x, v = LAPACK.stev!('V', collect(1.0:2:2*n-1),
> collect(1.0:n-1)) w = vec(v[1,:].^2) x, w end |
> 
> Would you mind registering this package so that people (I) can require
> it for other packages?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/billmclean/GaussQuadrature.jl/issues/2.

## 

---

A/Prof. William McLean                    tel: +61 2 9385 7045
School of Mathematics and Statistics      fax: +61 2 9385 7123
The University of New South Wales
Sydney 2052                               email: w.mclean@unsw.edu.au

## AUSTRALIA                                 CRICOS Code for UNSW: 00098G

**Comment by billmclean** [comment]
Hello Godisemo,
I have now registered GaussQuadrature.jl.  
Regards,
Bill McLean.
On Sun, 2015-10-11 at 07:31 -0700, Godisemo wrote:

> This package is a lot faster than my quick implementation for
> computing Laguerre quadrature points.
> function laguerre(n)
>   x, v = LAPACK.stev!('V', collect(1.0:2:2*n-1), collect(1.0:n-1))
>   w = vec(v[1,:].^2)
>   x, w
> end
> Would you mind registering this package so that people (I) can
> require it for other packages?
> —
> 
> ## Reply to this email directly or view it on GitHub.
> 
> ---
> 
> A/Prof. William McLean                     tel: +61 2 9385 7045
> School of Mathematics and Statistics       fax: +61 2 9385 7123
> The University of New South Wales
> Sydney 2052                                email: w.mclean@unsw.edu.au
> AUSTRALIA                                  CRICOS Code for UNSW: 00098G

## Associate Editor, Journal of Integral Equations and Applications.

**Comment by Godisemo** [comment]
Thanks a lot!
